### ISSUE TITLE
 TypeError: store.dispatch is not a function

### ISSUE THREAD

**Issue by b-asaf** [ferrannp/react-native-testing-example#2]
I am using JEST v20 and redux-mock-store v1.3.0.

I followed the code examples and I am getting the following errors:
 TypeError: _reduxMockStore2.default.dispatch is not a function

My mistake,
missed one important line: `const store = mockStore();`

**Comment by assafb81** [comment]
My mistake, 
missed one important line: `const store = mockStore();`
