### ISSUE TITLE
Executed Test Case is not passing

### ISSUE THREAD

**Issue by bkasturiwale** [ferrannp/react-native-testing-example#3]
Hello ,
I have recently started checking the React Native. I was checking this example but received following error while executing it. We would appreciate if we can get a link which provide detail level explanation for how to use this and debug it.

Appreciate the help.

> ReactNativeTestingExample@0.0.1 test /Users/globallogic/Documents/UnitTest_RN/react-native-testing-example
> jest "RepoItem-Snapshot-diff-test.js"

 FAIL  app/components/__tests__/RepoItem-Snapshot-diff-test.js
  ✕ checks a selected RepoItem (83ms)

  ● checks a selected RepoItem

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
      Snapshot Diff:
      - Base item
      + Selected item
      
    - @@ -26,4 +26,9 @@
    - -      Object {
    - -        "paddingHorizontal": 24,
    - -        "paddingVertical": 8,
    - -      }
    - +      Array [
    - +        Object {
    - +          "paddingHorizontal": 24,
    - +          "paddingVertical": 8,
    - +        },
    - +        Object {
    - +          "backgroundColor": "#B2DFDB",
    - +        },
    - +      ]
    + @@ -26,0 +26,1 @@
    + +       Array [
    + @@ -29,0 +30,5 @@
    + +         },
    + +         Object {
    + +           "backgroundColor": "#B2DFDB",
    + +         },
    + +       ]
    + @@ -30,1 +36,0 @@
    + -     }
      @@ -58,0 +63,7 @@
    - +    <Text
    - +      accessible={true}
    - +      allowFontScaling={true}
    - +      ellipsizeMode="tail"
    - +    >
    - +      Useful description goes here.
    - +    </Text>
    + +     <Text
    + +       accessible={true}
    + +       allowFontScaling={true}
    + +       ellipsizeMode="tail"
    + +     >
    + +       Useful description goes here.
    + +     </Text>
      
      at Object.<anonymous> (app/components/__tests__/RepoItem-Snapshot-diff-test.js:13:1)
      at tryCallTwo (node_modules/promise/lib/core.js:45:5)
      at doResolve (node_modules/promise/lib/core.js:200:13)
      at new Promise (node_modules/promise/lib/core.js:66:3)
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15

 › 1 snapshot test failed.
Snapshot Summary
 › 1 snapshot test failed in 1 test suite. Inspect your code changes or run with `npm test -- -u` to update them.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   1 failed, 1 total
Time:        0.862s, estimated 2s
Ran all test suites matching /RepoItem-Snapshot-diff-test.js/i.
npm ERR! Test failed.  See above for more details.

**Comment by bkasturiwale** [comment]
It is working if I change from _toMatchDiffSnapshot_ to _toMatchSnapshot_

**Comment by ferrannp** [comment]
What version of Jest are you using? There was some updates in the repository recently so I regenerated some snapshots. You should be able to pull changes and run `yarn` and everything should be fine. Unless you made changes locally to the repo, then you need to regenerate the snapshot yourself running `npm test -- --u`.
